agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
- label: ":key: Print Job Token"
  key: token
  command: .buildkite/steps/token
  parallelism: 2
- label: ":key: check job tokens are distinct"
  command: .buildkite/steps/check-tokens
  depends_on:
  - token
