agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
- key: setup
  label: setup
  command: |
    exit 0
  parallelism: 3
- key: one
  label: one
  command: |
    buildkite-agent step get outcome --step setup --build $BUILDKITE_BUILD_ID
  depends_on: setup
  allow_dependency_failure: true
