steps:
- label: empty step 1
  command:
  - sleep 20
  - echo 'build complete'

- wait: ~

- label: empty step 2
  command:
  - sleep 20
  - echo 'build complete'

- label: empty hidden step 1
  key: "build-complete"
  branches: "master"
  command:
  - sleep 20
  - echo 'build complete'

- wait: ~
  if: build.branch == "master"

- label: empty step 3
  command:
  - sleep 20
  - echo 'build complete'
