agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Sleep"
    command:
      - false && \
      - .buildkite/scripts/sleep.sh 60
    artifact_paths: tests/**
