agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: ":running: Versions"
    command: .buildkite/scripts/run.sh
  - label: "interpolate outside"
    command: echo "$BUILDKITE_AGENT_ACCESS_TOKEN"
  - label: "interpolate inside"
    command: echo "$$BUILDKITE_AGENT_ACCESS_TOKEN"
