agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: "upload relative artifact"
    command: |
      echo "relative llamas" > llamas.txt
      buildkite-agent artifact upload llamas.txt
      rm llamas.txt

      #   - label: "upload absolute artifact"
      #     command: |
      #       echo "absolute llamas" > /tmp/llamas.txt
      #       buildkite-agent artifact upload /tmp/llamas.txt
      #       rm /tmp/llamas.txt

  - wait

  - label: "download relative artifact"
    command: |
      shasum=$(buildkite-agent artifact shasum "llamas.txt")
      expected_shasum=fb60f84c2bd316e18a2f11e4da13684e41a16f31
      [[ \$shasum == \$expected_shasum ]] || echo expected: \$expected_shasum received: \$shasum && false
      buildkite-agent artifact download llamas.txt .
      exit_status=$(echo "ee756d1e307dc245b0df42f81845a4ff559531bc4cb287e35b15e4115844e903" | sha256sum --check)
      rm llamas.txt
      exit $exit_status

      #   - label: "download absolute artifact"
      #     command: |
      #       shasum=$(buildkite-agent artifact shasum "tmp/llamas.txt")
      #       expected_shasum=9ce999892fbca0da31b2a781b2730ac11a2fc8a2
      #       [[ \$shasum == \$expected_shasum ]] || echo expected: \$expected_shasum received: \$shasum && false
      #       buildkite-agent artifact download tmp/llamas.txt .
      #       exit_status=$(echo "e14227c78a206decdf9e869aaa2c44f3ff546a8324874e7442ef02b1f41a0099" | sha256sum --check)
      #       rm camels.txt
      #       exit $exit_status
