agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Versions"
    key: run
    command: .buildkite/steps/run
    plugins:
    - triarius/git-branch-assertion:
        some_key: some_value
        another_key: 4
    - improbable-eng/metahook:
        pre-checkout: |
          echo hello
        post-checkout: |
          echo $BUILDKITE_PLUGINS
    - triarius/test-hooks:
        some_key: some_value
        another_key: 6
