dag: true
agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - group: Test on each stack
    steps:
      - label: ":running: Versions on {{matrix}}"
        command: .buildkite/scripts/run.sh
      - label: Print Path on {{matrix}}
        command: .buildkite/scripts/print-path.sh
        artifact_paths: artifacts/*
    matrix:
      - v5.21.0-7-gb785427
      - v5.21.0-41-g49e62c1
    agents:
      buildkite-aws-stack: "{{matrix}}"
