agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
- label: ":running: Versions"
  key: run
  command: .buildkite/steps/run
  plugins:
  - docker-compose#v4.14.0:
      run: alpine
      ansi: false
      config: docker-compose.yaml
      mount-buildkite-agent: true
      propagate-environment: true
