agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
- key: setup
  label: setup
  command: exit %n
  parallelism: 3
- key: one
  label: one
  command: buildkite-agent step get outcome --step setup --build $$BUILDKITE_BUILD_ID
  depends_on: setup
