agents:
  queue: ${PIPELINE_QUEUE:-kubernetes}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: 🤫
    command: |-
      buildkite-agent secret get test-secret
  - label: ":running: Versions"
    key: run
    command: .buildkite/steps/run
  - label: ":key: JWT"
    key: jwt
    command: .buildkite/steps/jwt
  - label: ":key: Print Job Token"
    key: token
    command: .buildkite/steps/token
  - label: ":buildkite: test agent"
    depends_on:
      - token
    key: test-agent
    command: .buildkite/steps/test-agent
