agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Versions"
    command: .buildkite/scripts/run.sh
    plugins:
      - triarius/git-branch-assertion
