agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - group: "The best group ever"
    key: matrix
    steps:
      - label: "{{matrix.greeting}}"
        command: echo "{{matrix.greeting}} World"
        matrix:
           setup:
             greeting:
               - "Hello"
               - "G'day"
               - "Bonjour"
           adjustments:
             - skip: "skipping this"
               with:
                 greeting: "Hello"
             - skip: "skipping this"
               with:
                 greeting: "G'day"
             - skip: "skipping this"
               with:
                 greeting: "Bonjour"

  - label: ":running: Versions"
    command: .buildkite/scripts/run.sh
    depends_on: matrix
  - label: ":key: JWT"
    command: .buildkite/scripts/jwt.sh
    depends_on: matrix
  - label: "Print Job Token"
    command: .buildkite/scripts/token.sh
    depends_on: matrix
