agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Versions"
    key: run
    command: .buildkite/steps/run
  - label: ":key: JWT"
    key: jwt
    command: .buildkite/steps/jwt
  - label: ":key: Print Job Token"
    key: token
    command: .buildkite/steps/token
  - label: ":up: test upload"
    command:
      - echo "hello" > hello.txt
        cat hello.txt
        buildkite-agent artifact upload missing-file "missing-glob/*"
  - label: ":buildkite: test agent"
    depends_on:
      - token
    key: test-agent
    command: .buildkite/steps/test-agent
