agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: Test artifacts
    key: upload-artifacts
    parallelism: 2
    command:
      - mkdir -p artifacts
      - echo hello world! > artifacts/my_artifact.txt
    artifact_paths: artifacts/*
  - label: Download aritifacts
    depends_on:
      - upload-artifacts
    command:
      - mkdir -p artifacts
      - buildkite-agent artifact download artifacts/* artifacts/
      - ls -lA artifacts
      - cat artifacts/my_artifact.txt
