dag: true

env:
  LEVEL: "pipeline"
  BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"

agents:
  queue: ${PIPELINE_QUEUE:-default}

steps:
  - name: versions
    label: ":bash:"
    command: ./version.sh
  - name: jwt
    label: ":key: Obtain JWTs"
    command: ./jwt.sh
  - label: List files
    name: list_files
    command: ./run.sh
