dag: true

env:
  LEVEL: "pipeline"

steps:
  - name: versions
    label: ":bash:"
    command: ./version.sh
    agents:
      queue: ${PIPELINE_QUEUE:-default}
  - name: JWT
    label: ":key: JWT"
    command: ./jwt.sh
    agents:
      queue: ${PIPELINE_QUEUE:-default}
