agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - group: Best group ever
    steps:
    - label: "{{matrix.greeting}}"
      command: echo "{{matrix.greeting}} World"
      matrix:
         setup:
           greeting:
             - "Hello"
             - "G'day"
             - "Bonjour"
         adjustments:
           - skip: "skipping this"
             with:
               greeting: "Hello"
           - skip: "skipping this"
             with:
               greeting: "G'day"
           - skip: "skipping this"
             with:
               greeting: "Bonjour"

  - wait

  - label: ":running: Versions"
    command: .buildkite/scripts/run.sh
  - label: ":key: JWT"
    command: .buildkite/scripts/jwt.sh
  - label: "Print Job Token"
    command: .buildkite/scripts/token.sh
