agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: test parameter
    command: echo "$$BUNDLE_GEMS__CONTRIBSYS__COM"
    plugins:
      - triarius/aws-assume-role-with-web-identity#dont-expand-logs:
          role-arn: arn:aws:iam::253213882263:role/nepa-test-get-parameter
      - aws-ssm:
          parameters:
            BUNDLE_GEMS__CONTRIBSYS__COM: /nepa/nepas-test-org/test-parameter
