agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - command: echo "hello" $Foot $FOO
  - command: echo $$env:Foot $$env:FOO
  - command: bash -c 'echo $$Foot $$FOO $$FOOT'
