agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Versions"
    key: run
    command: .buildkite/steps/run
  - label: ":key: JWT"
    key: jwt
    command: .buildkite/steps/jwt
  - label: ":key: Print Job Token"
    key: token
    command: .buildkite/steps/token
  - label: Test artifacts
    key: upload-artifacts
    parallelism: 2
    command:
      - mkdir -p artifacts
      - echo hello world! > artifacts/my_artifact.txt
    artifact_paths: artifacts/*
  - label: Download aritifacts
    depends_on:
      - upload-artifacts
    command:
      - mkdir -p artifacts
      - buildkite-agent artifact download artifacts/* artifacts/
      - cat artifacts/my_artifact.txt
  - label: ":buildkite: test agent"
    depends_on:
      - token
    key: test-agent
    command: .buildkite/steps/test-agent
