agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Versions"
    key: run
    command: .buildkite/steps/run
    plugins:
    - triarius/git-branch-assertion:
        some_key: some_value
        another_key: 4
    - improbable-eng/metahook:
        pre-checkout: |
          echo hello
        post-checkout: |
          echo goodbye
    - triarius/test-hooks:
        some_key: some_value
        another_key: 6
  - label: ":key: JWT"
    key: jwt
    command: .buildkite/steps/jwt
  - label: ":key: Print Job Token"
    key: token
    command: .buildkite/steps/token
  - label: ":buildkite: test agent"
    depends_on:
      - token
    key: test-agent
    command: .buildkite/steps/test-agent
