agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: "🔨 Tests"
    command:
      - echo "Testing Symlinks, creating"
      - buildkite-agent artifact upload --upload-symlinks=false "symlinks/**/*"
