agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
env:
  FOO: bar
steps:
  - label: ":running: Versions"
    key: run
    command: .buildkite/steps/run
  - label: ":key: JWT"
    key: jwt
    env:
      FOO2: bar2
      FOO: bar2
    command: .buildkite/steps/jwt
