dag: true

env:
  LEVEL: "pipeline"

steps:
  - name: versions
    label: ":bash:"
    command: ./version.sh
    agents:
      queue: ${PIPELINE_QUEUE:-default}
  - name: jwt
    label: ":key: Obtain JWTs"
    command: ./jwt.sh
  - label: List file
    name: list_files
    command: ./run.sh
  - command: ./run.sh
    agents:
      queue: ${PIPELINE_QUEUE:-default}
