agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: ":running: Versions"
    command: .buildkite/scripts/run.sh
  - label: ":docker::ubuntu: build ubuntu"
    command: .buildkite/scripts/build.sh
