dag: true

env:
  LEVEL: "pipeline"
  BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"

agents:
  queue: ${PIPELINE_QUEUE:-default}

steps:
  - label: ":buildkite::bash: Print versions"
    command: ./version.sh
  - label: ":key: Obtain JWTs"
    command: ./jwt.sh
  - label: List files
    command: ./run.sh
  - label: ':rocket: Release'
    command: ./upload.sh
    plugins:
    - aws-assume-role-with-web-identity:
        role-arn: arn:aws:iam::253213882263:role/nepa-test-oidc
