agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Versions"
    command: .buildkite/scripts/run
  - label: ":key: JWT"
    command: .buildkite/scripts/jwt
  - label: ":key: Print Job Token"
    command: .buildkite/scripts/token
