agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: test parameter
    command: echo "$$BUNDLE_GEMS__CONTRIBSYS__COM"
    plugins:
      - triarius/aws-ssm:
          parameters:
            BUNDLE_GEMS__CONTRIBSYS__COM: /nepa/nepas-test-org/test-parameter
