agents:
  queue: ${PIPELINE_QUEUE:-kubernetes}
steps:
- label: 🤫
  command: |-
    printf "My agent job token is:\n%s\033[31m%s\033[0m\n" "$${BUILDKITE_AGENT_ACCESS_TOKEN:0:5}" "$${BUILDKITE_AGENT_ACCESS_TOKEN:5}"

    buildkite-agent secret get --debug --skip-redaction nepa-test

- label: "curl 🤫"
  command: |-
    curl -v "https://agent.buildkite.com/v3/jobs/$${BUILDKITE_JOB_ID}/secrets?key=nepa-test" -H "Authorization: Token $${BUILDKITE_AGENT_ACCESS_TOKEN}"
