agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: ":running: Versions"
    command: .buildkite/scripts/run.sh
    plugins:
      - docker#v3.5.0:
          image: "buildkite/agent:3.44.0"
          propagate-environment: true
  - label: ":key: JWT"
    command: .buildkite/scripts/jwt.sh
  - label: "Print Job Token"
    command: .buildkite/scripts/token.sh
  - label: "Print Job Token Again"
    command: .buildkite/scripts/token.sh
