x-anchors:
  matrix: &matrix
    - v5.21.0-7-gb785427
    - v5.21.0-55-g245cfc2
dag: true
agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - group: Versions
    steps:
      - label: ":running: Versions on {{matrix}}"
        command: .buildkite/scripts/run.sh
        agents:
          buildkite-aws-stack: "{{matrix}}"
        matrix: *matrix
  - group: Print Path
    steps:
      - label: Print Path on {{matrix}}
        command: .buildkite/scripts/print-path.sh
        artifact_paths: artifacts/*
        agents:
          buildkite-aws-stack: "{{matrix}}"
        matrix: *matrix
