agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: ":running: Versions"
    command: .buildkite/scripts/run.sh
  - label: ":key: JWT"
    command: .buildkite/scripts/jwt.sh
  - label: "Print Job Token"
    command: .buildkite/scripts/token.sh
  - label: "Print Job Token Again"
    command: .buildkite/scripts/token.sh

  - label: Sleep
    key: sleep
    command: sleep $${TEST_DURATION:-5}

  - label: Trigger Deploy
    trigger: deploy-pipeline
    depends_on: sleep
    async: true
