agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
- label: Encrypt with KMS key
  key: kms-encrypt
  plugins:
  - aws-assume-role-with-web-identity:
      role-arn: arn:aws:iam::172840064832:role/nepa-test-kms-access
  command: |-
    set -Eeufo pipefail

    echo -n "hello world!" \
    | base64 \
    | xargs -n1 aws kms encrypt --key-id arn:aws:kms:us-east-1:253213882263:key/e43ab8b1-e21c-48e4-953b-de0c66095148 --plaintext \
    | jq -r '.CiphertextBlob' \
    | base64 -d \
    > encrypted.blob
  artifact_paths:
  - encrypted.blob

- label: Decrypt with KMS key
  key: kms-decrypt
  depends_on:
  - kms-encrypt
  plugins:
  - aws-assume-role-with-web-identity:
      role-arn: arn:aws:iam::172840064832:role/nepa-test-kms-access
  command: |-
    set -Eeufo pipefail

    buildkite-agent artifact download encrypted.blob .

    echo -n "-- The encrypted message was:"
    aws kms decrypt --ciphertext-blob fileb://encrypted.blob --output text --query Plaintext \
    | base64 --decode
    echo
