agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: upload automatic artifact
    artifact_paths: artifacts/**/*
    command: |
      set -Eeufo pipefail
      mkdir -p artifacts/${BUILDKITE_BUILD_NUMBER}
      echo "automatic llamas" > artifacts/${BUILDKITE_BUILD_NUMBER}/llamas.txt
      curl -sSL https://buildkite.com/_site/favicon.png > artifacts/${BUILDKITE_BUILD_NUMBER}/logo.png
      curl -sSL https://buildkite.com/_site/favicon.png > "artifacts/${BUILDKITE_BUILD_NUMBER}/logo 1.png"

  - label: upload relative artifact
    command: |
      set -Eeufo pipefail

      trap "rm llamas.txt" EXIT

      echo "relative llamas" > llamas.txt
      buildkite-agent artifact upload llamas.txt

      shasum=$(buildkite-agent artifact shasum llamas.txt)
      expected_shasum=fb60f84c2bd316e18a2f11e4da13684e41a16f31
      if [[ \$shasum != \$expected_shasum ]]; then
        echo expected: \$expected_shasum received: \$shasum
        exit 1
      fi

  - label: upload absolute artifact
    command: |
      set -Eeufo pipefail

      trap "rm /tmp/llamas.txt" EXIT

      echo "absolute llamas" > /tmp/llamas.txt
      buildkite-agent artifact upload /tmp/llamas.txt

      shasum=$(buildkite-agent artifact shasum tmp/llamas.txt)
      expected_shasum=9ce999892fbca0da31b2a781b2730ac11a2fc8a2
      if [[ \$shasum != \$expected_shasum ]]; then
        echo expected: \$expected_shasum received: \$shasum
        exit 1
      fi

  - wait

  - label: show artifacts
    command: |
      set -Eeufo pipefail

      function inline_image {
        printf '\033]1338;url='"$1"';alt='"$2"'\a\n'
      }

      inline_image 'artifact://artifacts/205/logo 1.png' 'OMG'

  - label: download relative artifact
    command: |
      set -Eeufo pipefail

      trap "rm llamas.txt" EXIT

      buildkite-agent artifact download llamas.txt .
      echo "ee756d1e307dc245b0df42f81845a4ff559531bc4cb287e35b15e4115844e903 llamas.txt" | sha256sum --check

  - label: download absolute artifact
    command: |
      set -Eeufo pipefail

      trap "rm tmp/llamas.txt" EXIT

      buildkite-agent artifact download tmp/llamas.txt .
      echo "e14227c78a206decdf9e869aaa2c44f3ff546a8324874e7442ef02b1f41a0099 tmp/llamas.txt" | sha256sum --check
