agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
- label: Encrypt with KMS key
  key: kms-encrypt
  plugins:
  - aws-assume-role-with-web-identity:
      role-arn: arn:aws:iam::172840064832:role/nepa-test-kms-access
  command: |-
    set -Eeufo pipefail

    aws kms encrypt --key-id alias/nepa-test-kms-access --plaintext "hello world" --output text --query CiphertextBlob | base64 > encrypted.txt
  artifact_paths:
  - encrypted.txt
