agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - group: ":test_tube: run cluster tests"
    key: test
    steps:
    - label: ":running: Versions"
      command: sleep 120
      timeout_in_minutes: 1
  - key: destroy-staging
    async: true
    label: tear down test cluster
    trigger: nepa-test-2
    allow_dependency_failure: true
    depends_on:
    - test
