env:
  BUILDKITE_REDACTED_VARS: ""
steps:
  - label: plugin
    plugins:
      - kubernetes:
          a: &a
            a: *a
    matrix:
      setup:
        arch:
          - arm64
          - amd64
