agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Versions"
    command: .buildkite/scripts/run.sh
  - label: ":key: JWT"
    command: .buildkite/scripts/jwt.sh
  - label: "Print Job Token"
    command: .buildkite/scripts/token.sh
