agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Script"
    command: |
      echo $$-
      echo $$$$
      ps -eo pid,ppid,pgid,args | grep $$PPID
