agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Env"
    command: cat $$BUILDKITE_ENV_FILE
  - label: ":running: Sleep"
    command: .buildkite/scripts/sleep.sh
