agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: nepa-test-windows
steps:
  - label: ":running: Versions"
    command: .buildkite/scripts/run.sh
  - label: ":docker::windows: Run Hello World Docker"
    command: docker run mcr.microsoft.com/dotnet/samples:dotnetapp-nanoserver-2009
