agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: test parameter
    command: echo I am doing 🆒 stuff with the role that that I have!
    plugins:
      - triarius/aws-assume-role-with-web-identity#dont-expand-logs:
          role-arn: arn:aws:iam::253213882263:role/nepa-test-get-parameter
