dag: true

env:
  LEVEL: "pipeline"
  BUILDKITE_PLUGINS_ALWAYS_CLONE_FRESH: "true"

agents:
  queue: ${PIPELINE_QUEUE:-default}

steps:
  - label: ":buildkite::bash: Print versions"
    command: .buildkite/scripts/version.sh
  - label: ":key: Obtain JWTs"
    command: .buildkite/scripts/jwt.sh
  - label: List files
    command: .buildkite/scripts/run.sh
  - if: build.branch == 'main'
    label: ':rocket: Release'
    command: .buildkite/scripts/upload.sh
    plugins:
     aws-assume-role-with-web-identity:
        role-arn: arn:aws:iam::253213882263:role/nepa-test-oidc
