dag: true

env:
  LEVEL: "pipeline"

steps:
  - name: versions
    label: ":bash:"
    command: ./run.sh
    plugins:
      - file://./.buildkite/plugins/vendored
    agents:
      queue: ${PIPELINE_QUEUE:-default}
