x-anchors:
  common: &common
    plugins:
      - triarius/git-branch-assertion: ~

agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
  - label: ":running: Versions"
    key: run
    command: .buildkite/steps/run
    <<: *common
