agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
- command: echo hello world
  plugins:
  - detect-clowns:v2.0.0: ~
- command: echo hello world
  plugins:
  - detect-clowns:v2.0.0
- command: echo hello world
  plugins:
    detect-clowns:v2.0.0: ~
- command: echo hello world
  plugins:
    - detect-clowns:v2.0.0
