agents:
  queue: ${PIPELINE_QUEUE:-default}
steps:
  - label: Test Plugin Env
    plugins:
      - .buildkite/plugins/env-tester:
          foo - it is a key! - wow:
            bar: 1
          parameters:
            BUNDLE_GEMS__CONTRIBSYS__COM: /nepa/nepas-test-org/test-parameter
