agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
- key: check-env
  command: echo $$BUILDKITE_TERMINATE_INSTANCE_AFTER_JOB
- key: check-interpolated
  command: echo $BUILDKITE_TERMINATE_INSTANCE_AFTER_JOB
