agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: nepa-test-tajw
steps:
  - label: ":running: Versions"
    key: run
    command: .buildkite/steps/run
  - label: ":buildkite: test agent"
    depends_on:
      - run
    key: test-agent
    command: .buildkite/steps/test-agent
