agents:
  queue: ${PIPELINE_QUEUE:-default}
  stack: ${PIPELINE_STACK:-*}
steps:
- label: ":running: Versions"
  key: run
  command: |
    mkdir tmp/artifacts
    echo "Hello, world!" > tmp/artifacts/hello.txt
    echo "Hello, world!" > tmp/artifacts/hello2.txt
  plugins:
  - docker-compose#v4.14.0:
      run: alpine
      ansi: false
      config: docker-compose.yaml
      mount-buildkite-agent: true
      propagate-environment: true
  artifact_paths: tmp/artifacts/*
