dag: true

env:
  LEVEL: "pipeline"

steps:
  - command: ./run.sh
    plugins:
      - file://./.buildkite/plugins/vendored
      - sj26/oidc-token: {}
    agents:
      queue: ${PIPELINE_QUEUE:-default}
