#!/usr/bin/env bash

set -Eeuo pipefail

export MY_VALUE="muggier quasi stupefy dedicated"

echo This a secret: "$MY_VALUE", it should not be redacted yet.

echo "$MY_VALUE" | buildkite-agent log redact

echo This a secret: "$MY_VALUE", it should be redacted now.
