#!/usr/bin/env bash

set -Eeuo pipefail

trap "echo pre-exit terming..." SIGTERM

echo "in pre-exit..."

echo pid: $$
ps -eo pid,ppid,pgid,args | grep $$

echo parent pid: $PPID
ps -eo pid,ppid,pgid,args | grep $PPID

echo search for bash processes
pgrep bash

echo search for sleep processes
pgrep sleep
