#!/usr/bin/env bash

set -Eeuo pipefail

trap "echo pre-exit terming..." SIGTERM

echo "in pre-exit..."

echo printing process tree of grandparent
pstree -hp "$(ps -o ppid= -p $PPID | xargs)"

echo search for bash processes
pgrep bash || echo no bash processes found

echo search for sleep processes
pgrep sleep || echo no sleep processes found
