#!/usr/bin/env bash

set -Eeuo pipefail

trap "echo pre-exit terming..." SIGTERM

echo "in pre-exit..."

echo printing process tree of grandparent
pstree -hp "$(ps -o ppid= -p $PPID | xargs)"

echo search for bash processes
pgrep bash

echo search for sleep processes
pgrep sleep
