#!/usr/bin/env bash

set -Euxo pipefail

buildktie-agent --help
buildkite-agent --version

buildkite-agent annotate "Hello 👋 from the buildkite-agent bootstrap script"
buildkite-agent annotation remove
buildkite-agent artifact upload README.md
buildkite-agent artifact download README.md
buildkite-agent artifact search README.md
buildkite-agent artifact shasum README.md
buildkite-agent artifact download README.md /tmp/README.md

buildkite-agent meta-data set hello <<<"Hello 👋 from the buildkite-agent bootstrap script"
buildkite-agent meta-data get hello
buildkite-agent step get --step token
