#!/usr/bin/env bash

set -Eeufo pipefail

failure() {
  local lineno=$1
  local msg=$2
  echo "Failed at $lineno: $msg" >&2
}

trap 'failure ${LINENO} "$BASH_COMMAND"' ERR

docker buildx build --progress=plain -t jwt:latest -f .buildkite/Dockerfile .

jwt() {
  docker run --rm -i -e FORCE_COLOR=3 jwt:latest
}

echo --- :key: OIDC Tokens

buildkite-agent oidc request-token \
  --claim agent_created_at \
  --claim env.FOO1 \
  --claim env.FOO2 \
  --claim env.FOO12 \
  | jwt
buildkite-agent oidc request-token --claim env.NOT_FOO | jwt
