#!/usr/bin/env bash

set -Eeuo pipefail

echo "$MY_SECRET is redeacted, as it was set as a secret a previous hook."

SECRET="🤫post-checkout🤫"
echo "$SECRET is not redacted, despite being set as a secret caught by the redactor in a previous hook."
