#!/usr/bin/env bash

set -Eeuo pipefail

print_secrets() {
  echo This a secret: 🎉💜👍
}

print_secrets

buildkite-agent secret redact <<SECRETS
🎉💜👍
SECRETS

print_secrets

buildkite-agent secret get TEST_SECRET

echo "$MY_VALUE"
