#!/usr/bin/env bash

set -Eeuxo pipefail

buildkite-agent --help
buildkite-agent --version

buildkite-agent annotate "Hello 👋 from the buildkite-agent bootstrap script"
buildkite-agent annotate --context remove-me "⚠️ this annotation should have been be removed"
buildkite-agent annotation remove --context remove-me
buildkite-agent artifact upload ".buildkite/steps/*"

mkdir -p tmp/steps
buildkite-agent artifact download '.buildkite/steps/*' tmp/steps
ls -lAR tmp/steps

buildkite-agent artifact search .buildkite/steps/test-agent
buildkite-agent artifact shasum .buildkite/steps/jwt

buildkite-agent meta-data set hello <<<"Hello 👋 from the buildkite-agent bootstrap script"
buildkite-agent meta-data get hello
buildkite-agent step get --step token --format json
